config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :blogs
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get '/', to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :content, presence: true
end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feeds, dependent: :destroy
  has_many :lists, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contact_path(@contact.id), notice: "お問い合わせ完了しました！"
    else
      # 入力フォームを再描画します。
      render :new
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  private

  def contact_params
  params.require(:contact).permit(:name, :email, :content, :title)
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @feed.save
        redirect_to @feed, notice: 'Feed was successfully created.'
      else
        render :new
      end
    end
  end



  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    render :new if @feed.invalid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_feed
  @feed = Feed.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def feed_params
  params.require(:feed).permit(:image, :image_cache, :content, :name)
  end
end

app/controllers/lists_controller.rb
# class ListsController < ApplicationController
#   before_action :set_list, only: [:show, :edit, :update, :destroy]
#
#
#   def index
#     @lists = List.all
#   end
#
#   def show
#   end
#
#   def new
#     @list = List.new
#   end
#
#   def edit
#   end
#
#   def create
#     @list = current_user.lists.build(list_params)
#
#     respond_to do |format|
#       if @list.save
#         format.html { redirect_to @list, notice: 'List was successfully created.' }
#         format.json { render :show, status: :created, location: @list }
#       else
#         format.html { render :new }
#         format.json { render json: @list.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#   def confirm
#     @list = current_user.lists.build(list_params)
#
#     render :new if @list.invalid?
#   end
#
#   def update
#     respond_to do |format|
#       if @list.update(list_params)
#         format.html { redirect_to @list, notice: 'List was successfully updated.' }
#         format.json { render :show, status: :ok, location: @list }
#       else
#         format.html { render :edit }
#         format.json { render json: @list.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   def destroy
#     @list.destroy
#     respond_to do |format|
#       format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#     # Use callbacks to share common setup or constraints between actions.
#   def set_list
#   @list = List.find(params[:id])
#   end
#
#       # Never trust parameters from the scary internet, only allow the white list through.
#   def list_params
#   params.require(:list).permit(:content)
#   end
# end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        # 保存の成功した場合の処理
        redirect_to user_path(@user.id)
      else
        render 'new'
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @users = User.all
  end

  def confirm
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice:"ブログを削除しました！"
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  private

  def set_user
  @user = User.find(params[:id])
  end

  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # def choose_new_or_edits
  #   if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
  #     confirm_users_path
  #
  #   elsif action_name == 'edit'
  #     user_path
  #   end
  # end
end

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>


    <div class="btn" id = "change-text">人生と向き合う</div>

  <!-- 2つ目の<div>タグに、"change-html"というidをつけてください -->
    <div class="btn" id = "change-html">人生をチェンジ</div>
    <h1 id="text">人生を変えるためのチャンスをつかもう</h1>


  <div id ="language-wrapper">
    <h1 class="language-title">人生を謳歌していますか?</h1>
    <p class="language-text">
      満足な人生を歩むために、何が必要か考えてみましょう。金か、友達か、スキルか、様々な資産がある中で、あなたの強みの資産、弱みの資産を堂々と言えることができますか?
    </p>
  </div>






    <!-- <div class="message-wrapper">
        <ul class="faq-list">
            <li class="faq-list-item">
                <h3 class="question">毎日輝かしい人生にすることはできますか？</h3>
                <span>+</span>
                <div class="answer">できます。</div>
            </li>
            <li class="faq-list-item">
                <h3 class="question">過去を断ち切ることはできますか？</h3>
                <span>+</span>
                <div class="answer">できます。</div>
            </li>
            <li class="faq-list-item">
                <h3 class="question">夢を叶えられますか？</h3>
                <span>+</span>
                <div class="answer">できます。</div>
            </li>
        </ul>
    </div> -->





</body>
</html>

app/views/contacts/index.html.erb
<h1>A</h1>

app/views/contacts/new.html.erb
<header>
  <div class="container">
    <div class="header-title">
      <div id="top-btn" class="header-logo">人生</div>
    </div>
    <div class="header-menu">
      <ul class="header-menu-right">

        <li>
          <!-- <a href="#contact/index">お問い合わせ</a> -->
          <%= link_to 'contact/index', @contact %>

        </li>
      </ul>
    </div>
  </div>
</header>
<%= form_with(model: @contact, local: true) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>



<div id="contact" class="contact-section gray-section">
  <div class="contact-section-inner">
    <div class="container">
      <div class="section-title">
        <h3>お問い合わせ</h3>
      </div>
      <div class="contact-form">
        <h4>メッセージを送る</h4>

          <!-- <div class="error-message"></div>
          <input type="text" name="name" placeholder="お名前" class="contact-name">
          <div class="error-message"></div>
          <input type="text" name="email" placeholder="メールアドレス" class="contact-email"> -->

        <%= form_with(model: @contact, local: true) do |form| %>
          <!-- <div class="error-message"></div>
          <textarea name="message" placeholder="メッセージ内容"></textarea> -->
          <div class="contact_name">
            <%= form.label :name %>
            <%= form.text_field :name %>
          </div>
          <div class="contact_name">
            <%= form.label :email %>
            <%= form.text_field :email %>
          </div>
          <div class="contact_title">
            <%= form.label :title %>
            <%= form.text_field :title %>
          </div>
          <div class="contact_title">
            <!-- <textarea name="message" placeholder="メッセージ内容"></textarea> -->

            <%= form.label :content %>
            <%= form.text_field :content %>
          </div>

          <%= form.submit "おはよう", class: "btn btn-contact"%>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<p>名前: <%= @contact.name %></p>
<p>メール: <%= @contact.email %></p>
<p>タイトル: <%= @contact.title %></p>
<p>内容: <%= @contact.content %></p>

app/views/feeds/_form.html.erb
<%= form_with(model: @feed, local: true, url: choose_new_or_edit) do |form| %>
  <div class="field">
    <%= form.label :image %>
    <%= form.label :content %>
    <%= form.text_area :content %>

    <%= form.label :image %>
    <%= form.file_field :image %>
    <!-- 確認画面から新規作成画面に戻った時に、 -->
    <!-- アップロードした画像を表示させるための記述 -->
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>

    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>
<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= image_tag feed.image.url if feed.image.url %></td>
        <td><%= feed.user.name %></td>
        <td><%= feed.content %></td>

        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>
<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url if @feed.image.url %>
</p>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Facebook</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/feeds">Facebook</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

            <li><a href="/blogs" class="btn login">人生について</a></li>
            <li><a href="/contacts/new" class="btn signup">お問い合わせ</a></li>
            <li><a href="/users" class="btn login">ユーザー一覧</a></li>
            
            <% if logged_in? %>
              <%= link_to "Profile", user_path(current_user.id) %>
              <%= link_to "Logout", session_path(current_user.id), method: :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_path %>
              <%= link_to "Login", new_session_path %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>


    <%= yield %>
    <footer>
    </footer
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %>
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <%= image_tag list.user.image.url if list.user.image.url %>
        <td><%= list.user.name %></td>
        <td><%= list.content %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @list.content %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/users/_form.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true ) do |f| %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @user, local: true) do |form| %>



  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!DOCTYPE html>


<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.image.url if user.image.url %></td>
        <td><%= user.name %></td>
        <td><%= user.content %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_user_path %>

app/views/users/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <% if @user.image.url.present? %>
    <%= image_tag @user.image.url if @user.image.url %>
  <% end %>

</p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @user.content %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>